apiVersion: external-secrets.io/v1
kind: ClusterSecretStore 
metadata: 
    name: vault-backend
    namespace: kube-system  #
spec: 
    provider: 
        vault: 
            server: "http://vault-public.manupanand.online:8200"  
            path: "roboshop-k8s"
            version: "v2"  
            auth: 
                tokenSecretRef: 
                    name: "vault-token"
                    key: "token" 
                    namespace: "roboshop" # very important <- point where token is stored, token must be in application ns
                    