controller: 
  name: haproxy-controller
  ingressClass: haproxy
  service: 
    type: LoadBalancer 
    annotations: 
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb" #"nlb"  # or "external"-external is classic
      service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-south-2:058264470882:certificate/47a1d684-7a5d-49bd-b80f-8089c205d94c
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
      external-dns.alpha.kubernetes.io/hostname: devtest.manupanand.online
      haproxy.org/ssl-redirect: "false"
defaultBackend: 
  enabled: true 

rbac: 
 create: true
    