controller:  # configration for ingres to open http and https ports in LB
  service: 
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-south-2:058264470882:certificate/b85beb43-66bd-4d7e-a23c-e075db3b4d9e
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
# see values.yaml