controller:  # configration for ingres to open http and https ports in LB
  service:
    type: LoadBalancer
    targetPorts: 
      http: http 
      https: https  
    annotations:
      external-dns.alpha.kubernetes.io/hostname: frontend.manupanand.online
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-south-2:058264470882:certificate/47a1d684-7a5d-49bd-b80f-8089c205d94c
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
      service.beta.kubernetes.io/aws-load-balancer-listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    config: 
      ssl-redirect: "true" # enable ssl redirect globbaly at controller level
# see values.yaml