#helm-charts/charts/kube-prometheus-stack/value.yaml-> grafana , ingress,enabled>false
grafana:
#  service: 
#    type: NodePort #change to node port by default it is clusterip
 ingress: 
   enabled: true  # by default paths: /*
   ingressClassName: alb
   annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing 
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/group.name: roboshop # to group similar load balancer
      alb.ingress.kubernetes.io/healtcheck-path: /login
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-south-2:058264470882:certificate/b85beb43-66bd-4d7e-a23c-e075db3b4d9e
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
      alb.ingress.kubernetes.io/ssl-redirect: "443"
      #alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}' 
prometheus:
#  service: 
#    type: NodePort
 ingress: 
   enabled: true
   paths: 
     - /*  # by default it is / changed it to /*
   ingressClassName: alb 
   annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing 
      alb.ingress.kubernetes.io/target-type: ip #instance nodeport may be needed
      alb.ingress.kubernetes.io/group.name: roboshop
      alb.ingress.kubernetes.io/healtcheck-path: /login
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-south-2:058264470882:certificate/b85beb43-66bd-4d7e-a23c-e075db3b4d9e
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
      alb.ingress.kubernetes.io/ssl-redirect: "443"
      #alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}' 
# apply using helm release>values