#source common.sh
- name: Setting prompt name
  ansible.builtin.lineinfile:
     path: "/home/ec2-user/.bashrc"
     line: 'export PS1="\[\e[1;31m\]\u\[\e[0m\]@\[\e[1;34m\]{{ role_name }}\[\e[0m\] \w \$ "'
     create: true
     mode: '0644'

- name: Source the updated .bashrc
  ansible.builtin.shell: |
    source  /home/ec2-user/.bashrc
  args:
    executable: /bin/bash 


- name: Copy mysql repo
  ansible.builtin.copy:
    src: mysql-community.repo
    dest: /etc/yum.repos.d/mysql-community.repo


- name: Installing mysql
  ansible.builtin.dnf:
    name:  mysql-community-server
    state: latest

- name: Enable- start Mysql
  ansible.builtin.systemd_service:
    name: mysqld
    state: restarted
    enabled: true

- name: Extract MySQL temporary root password
  ansible.builtin.shell: "grep 'temporary password' /var/log/mysqld.log | awk '{print $NF}'"
  register: mysql_temp_pass

- name: Set MySQL root password
  ansible.builtin.shell: |
    mysql --connect-expired-password -uroot -p'{{ mysql_temp_pass.stdout }}' \
      -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'RoboShop@1';"
  args:
    executable: /bin/bash


- name: Enabling ports with firewalld
  ansible.builtin.shell: | 
     firewall-cmd --zone=public --add-port=22/tcp --permanent  && firewall-cmd --reload
     firewall-cmd --zone=public --add-port=3306/tcp --permanent  && firewall-cmd --reload
     firewall-cmd --zone=public --add-port=80/tcp --permanent  && firewall-cmd --reload
     firewall-cmd --zone=public --add-port=443/tcp --permanent  && firewall-cmd --reload
  args:
    executable: /bin/bash 


- name: Enable- start Mysql
  ansible.builtin.systemd_service:
    name: mysqld
    state: restarted
    enabled: true

# for future use
# - name: Store MySQL root credentials for future use
#   copy:
#     dest: /tmp/.my.cnf
#     content: |
#       [client]
#       user=root
#       password=RoboShop@1
#     owner: root
#     group: root
#     mode: '0600'
