#source common.sh
- name: Setting prompt name
  ansible.builtin.lineinfile:
     path: "/home/ec2-user/.bashrc"
     line: 'export PS1="\[\e[1;31m\]\u\[\e[0m\]@\[\e[1;34m\]{{ role_name }}\[\e[0m\] \w \$ "'
     create: true
     mode: '0644'

- name: Source the updated .bashrc
  ansible.builtin.shell: |
    source  /home/ec2-user/.bashrc
  args:
    executable: /bin/bash 


- name: Copy mysql repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mysql-community.repo


- name: Installing mysql
  ansible.builtin.dnf:
    name:  mysql-community-server
    state: latest

- name: Enable- start Mysql
  ansibe.builtin.systemd_service:
    name: mysqld
    state: restarted
    enabled: true

# this will later on aws a service
- name: Setting mysql root password
  ansibe.builtin.shell: |
   mysql_secure_installation --set-root-pass RoboShop@1

- name: Enabling ports with firewalld
  ansible.builtin.shell: | 
     firewall-cmd --zone=public --add-port=22/tcp --permanent  && firewall-cmd --reload
     firewall-cmd --zone=public --add-port=3306/tcp --permanent  && firewall-cmd --reload
     firewall-cmd --zone=public --add-port=80/tcp --permanent  && firewall-cmd --reload
     firewall-cmd --zone=public --add-port=443/tcp --permanent  && firewall-cmd --reload
  args:
    executable: /bin/bash